version: '3'
services:
  config-server:
    build: ./config-server
    image: barathece91/spring-cloud-gateway-config-server
    ports:
      - "8888:8888"
  eureka-server:
    build: ./eureka-server
    image: barathece91/spring-cloud-gateway-eureka-server
    ports:
      - "9000:9000"
    depends_on:
     - config-server
  bank-service:
    build: ./bank-microservice
    image: barathece91/spring-cloud-gateway-bank-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9000/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  customer-service:
    build: ./customer-microservice
    image: barathece91/spring-cloud-gateway-customer-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9000/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  api-cloud-gateway:
    build: ./api-cloud-gateway
    ports:
      - "8500:8500"
    depends_on: 
      - config-server
      - eureka-server
      - customer-service
      - bank-service
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.default-zone": "http://eureka-server:9000/eureka",
        "spring.cloud.config.uri": "http://config-server:8888",
        "spring.cloud.gateway.routes":
        [
          {
            "id": "bank-service",
            "uri": "http://bank-service:8081",
            "predicates": [ "Path= /bankms/**" ],
            "filters": [ "StripPrefix=1" ]
          },
          {
            "id": "customer-service",
            "uri": "http://customer-service:8082",
            "predicates": [ "Path= /customerms/**" ],
            "filters": [ "StripPrefix=1" ]
          }
        ]
      }'
