version: '3.7'
services:
  config-server:
    build: ./config-server
    image: barathece91/spring-cloud-gateway-config-server
    ports:
      - "8888:8888"
  eureka-server:
    build: ./eureka-server
    image: barathece91/spring-cloud-gateway-eureka-server
    ports:
      - "8080:8080"
    depends_on:
     - config-server
  bank-service:
    build: ./bank-microservice
    image: barathece91/spring-cloud-gateway-bank-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  customer-service:
    build: ./customer-microservice
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  api-cloud-gateway:
    build: ./zuul-proxy
    ports:
      - "8085:8085"
    depends_on: 
      - config-server
      - eureka-server
      - eureka-client-app1
      - eureka-client-app2
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka
      ZUUL_ROUTES_CLIENT1_URL: http://eureka-client-app1:8081
      ZUUL_ROUTES_CLIENT2_URL: http://eureka-client-app2:8082
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888