server:
  port: 8082
  

spring:
  application:
    name: customer-microservice
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
logging:
  level:
    org.springframework.web:  info
    web: debug
