  
spring:
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: http://bank-service:8081
          predicates:
          - Path= /bankms/*
          filters:
          - StripPrefix=1
        - id: customer-service
          uri: http://customer-service:8082
          predicates:
          - Path= /customerms/*
          filters:
          - StripPrefix=1
