
  
spring:
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: http://bank-service:8081
          predicates:
          - Query= service,bankms
        - id: airtel-service
          uri: http://customer-service:8082
          predicates:
          - Query= service,customerms
