  
spring:
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: http://bank-service:8081
          predicates:
          - Header= service,bank
        - id: customer-service
          uri: http://customer-service:8082
          predicates:
          - Header= service,customer
