
  
spring:
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: http://localhost:8081
          predicates:
          - Query= service,bankms
        - id: airtel-service
          uri: http://localhost:8082
          predicates:
          - Query= service,customerms
