server:
  port: 8081

spring:
  application:
    name: bank-microservice


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka # value will get overriden if passed from external config
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
